pipeline:
  publish:
    image: plugins/docker
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    repo: gopherci/gopherci-env
    tags: latest

  notify:
    email:
      from: noreply@github.com
      host: smtp.mailgun.org
      port: 587
      username: ${MAILGUN_USERNAME}
      password: ${MAILGUN_PASSWORD}
      recipients:
        - brad@teambrad.net
    when:
      status: [ success, failure ]
